### PR TITLE
Added some objects to support posts media

### PR DESCRIPTION
**Pull request by mehdiirh**
I added some api_objects to handle messages which shared a post in direct

### CODE REVIEW

**Comment by sumnerevans** [comment]
Could you please add some explanation of how to create such messages from within LinkedIn?

**Comment by mehdiirh** [comment]
> Could you please add some explanation of how to create such messages from within LinkedIn?

Just by sharing posts in direct
Tap "Send" within a post

**Comment by mehdiirh** [comment]
Hi @sumnerevans ,
 just wanted to remember you, please merge this PR if it's ok. otherwise, let me know and I'll fix the problems, I personally need to have these in PyPI. 

Thank you in advance

**Review by sumnerevans — APPROVED** [review]
Looks good. Please fix the linter errors (just running `black` should be sufficient I think).

**Comment by mehdiirh** [comment]
I don't see details in the logs, do you know what causes this error?

**Comment by sumnerevans** [comment]
What causes the error is not running `black` to format the files.

**Comment by mehdiirh** [comment]
it should work know

**Pull request merged**
